In [5]:
### load in numpy
import numpy as np

In [3]:
x = [1,2,3,4,5,6]


In [5]:
print(x)

[1, 2, 3, 4, 5, 6]


In [7]:
print(type(x))

<class 'list'>


In [11]:
np_x = np.array(x)

In [13]:
print(np_x)

[1 2 3 4 5 6]


In [15]:
print(type(np_x))

<class 'numpy.ndarray'>


In [24]:
#python lists
L = range(1000)
%timeit [X**2 for X in L]

135 μs ± 1.08 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [26]:
x = np.arange(1000)
%timeit x**2

2.02 μs ± 4.79 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Creating arrays

In [7]:
#1-D
x = np.array([0,1,2,3])
x

array([0, 1, 2, 3])

In [34]:
#print edimensions
x.ndim

1

In [38]:
#shape
x.shape

(4,)

In [3]:
import numpy as np
a = np.random.randint(0,20,5)
np

<module 'numpy' from 'C:\\Users\\subha\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [5]:
# 2-D
y = np.array([[0,1,2],[3,4,5]])
y

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
y.ndim

2

In [9]:
y.shape

(2, 3)

In [11]:
#3D
z = np.array([[[0,1],[2,3]], [[4,5],[6,7]]])
z

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
z. ndim

3

In [15]:
z.shape

(2, 2, 2)

### Creating array from a list

In [9]:
# we know how to create a list, right
my_list = [1,2,3]
my_list

[1, 2, 3]

In [20]:
np.array(my_list)

array([1, 2, 3])

In [22]:
# we can convert a matrix is also  a list to array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.array(my_matrix).shape

(3, 3)

### Function 

### arange

In [11]:
#using arange function -->arange is an array-valued version of the built-in python range 
#function 
x = np.arange(10) # 0.... n-1
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
y = np.arange(1,10,2) #start, end(exclusive),step
y

array([1, 3, 5, 7, 9])

### Linspace

In [13]:
#using linspace
x = np.linspace(0,5,6)
x

array([0., 1., 2., 3., 4., 5.])

In [49]:
# I want to get 3 evenly spaced points between 0 to 15
np.linspace(0,15, 8)

array([ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857,
       10.71428571, 12.85714286, 15.        ])

### zeros to ones

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
y = np.zeros((4,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
x = np.ones((2,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### eye

In [15]:
z = np.eye(4) #return a 2-D array with ones on the diagonal and zeros elsewhere.
z

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
d = np.eye(2,4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [17]:
#create array using diag function
x = np.diag([3,4,6,8])
x

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [72]:
np.diag(x)

array([3, 4, 6, 8])

In [19]:
#radiant -- return random integers from start (inclusive) to end (exclusive).
random_array = np.random.randint(1,125,6)
print(random_array)

[ 48  30 110  22  50  36]


In [80]:
#rand -- craete an array of the given shape and populate it with random samples from
#a uniform distribution over [0,1].
x= np.random.rand(5)
x

array([0.46583987, 0.46972583, 0.49352484, 0.11714168, 0.08829963])

In [21]:
#randn -- return a sample (or samples) from the "standard normal" distribution.***gausian***
x = np.random.randn(100)
x

array([ 0.3496924 , -0.50826412, -1.47936722,  0.7210474 ,  0.39824418,
       -1.62050792,  0.39347604,  0.91811606, -0.18295186,  0.35464089,
       -0.89570333,  0.87346641, -0.61134789, -0.36813672,  0.63602867,
       -0.38901955,  1.41166334,  0.12184091,  0.18274723, -0.5162857 ,
        0.36029696, -1.16789745, -0.09627978,  0.69308294,  0.93390297,
       -0.75385277,  1.24467594, -0.59674413,  1.08990225, -0.47657312,
        1.14168472,  0.16624793,  0.33062458,  1.2339494 , -0.73496145,
        1.95953105, -1.43165693, -2.02780758, -2.10490593,  0.01688418,
       -0.31545955, -0.47346573,  2.38352512, -0.1212885 ,  0.58288224,
        0.6565555 ,  0.63111541,  0.33747586,  1.72419026,  0.49151204,
        0.27441409, -0.84360219,  1.29398422, -0.54477524, -0.00979728,
       -1.07316664, -0.76344447,  0.39237755,  0.2569125 ,  0.88830275,
       -0.42390177,  0.13893887,  0.34892207, -0.65197933,  1.77390198,
       -0.26175802, -2.43937176, -1.05569816,  1.26735536,  0.60

### Copy array

In [23]:
x = np.array([1,2,3])
y = x
y[0] = 100
print(x)
print(y)

[100   2   3]
[100   2   3]


### Reshape array

In [25]:
arr = np.arange(20)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [27]:
#notice the two sets of brackets
x1=arr.reshape(4,5)
x1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print("shape of x: {}".format(x.shape))

[[1 2 3]
 [4 5 6]]
shape of x: (2, 3)


In [31]:
# reshaping
y = x.reshape(3,2)
print(y)
print("shape of y: {}".format(y.shape))

[[1 2]
 [3 4]
 [5 6]]
shape of y: (3, 2)


### Transpose array

In [33]:
x = np.array([[1,2,3],[4,5,6]])
print("shape: {}".format(x.shape))
print(x)

shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [113]:
z = x.T
print(z)

[[1 4]
 [2 5]
 [3 6]]


### Flattening

In [35]:
x = np.array([[1,2,3],[4,5,6]])
x.ravel()

array([1, 2, 3, 4, 5, 6])

In [118]:
z.ravel()

array([1, 4, 2, 5, 3, 6])

### Sorting

In [37]:
#sorting along an axis:
# axis=1 -->row and axis=0 -->column
x = np.array([[5,4,7],[2,9,6]])
y = np.sort(x , axis=1)
y

array([[4, 5, 7],
       [2, 6, 9]])

### Add/ remove array

In [39]:
x = np.array([4,7,8])
x = np.append(x,[2,5,4])
print('numpy array after addition:',x)

numpy array after addition: [4 7 8 2 5 4]


In [41]:
x = np.delete(x,4)
print('numpy array after deletion of one element:',x)

numpy array after deletion of one element: [4 7 8 2 4]


### indexing

In [48]:
x = np.arange(4,8)
print(x)
print(x[3])

[4 5 6 7]
7


In [54]:
# for multidimensional arrays, indexes are tuples of integers:
x = np.diag([4,5,6])
print(x)
print(x[1,2])

[[4 0 0]
 [0 5 0]
 [0 0 6]]
0


In [56]:
x[1,2] = 4
x

array([[4, 0, 0],
       [0, 5, 4],
       [0, 0, 6]])

### Slicing

In [59]:
x = np.arange(4,16)
x

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
x[1:4:2]

array([5, 7])

In [63]:
#we can also combine assignment and slicing:
x = np.arange(8)
x[4:]

array([4, 5, 6, 7])

In [65]:
x[4:]

array([4, 5, 6, 7])

In [67]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [69]:
y[::-2]

array([3, 1])

In [73]:
x[4:]=y[::-1]

In [75]:
x

array([0, 1, 2, 3, 3, 2, 1, 0])

### Fancy Indexing

In [8]:
import numpy as np
a = np.random.randint(0,20,5)
np

<module 'numpy' from 'C:\\Users\\subha\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [43]:
#matrix multiplication
a = np.array([[1,2,1],[3,4,3],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])
print('matrix multiplication:\n',np.matmul(a,b))

matrix multiplication:
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


In [12]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [14]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])

np.logical_or(a,b)

array([ True,  True,  True, False])

In [26]:
a = np.array([1,1,6,7],dtype=int)
b = np.array([1,3,1,2],dtype=int)
a+b
#np.logical_or(a,b)

array([2, 4, 7, 9])

In [29]:
a+b

array([2, 4, 7, 9])

In [33]:
a = np.array([1,1,0,0],dtype=float)
b = np.array([1,0,1,0],dtype=float)
a+b
#np.logical_or(a,b)

array([2., 1., 1., 0.])

### Operations

In [78]:
x = np.array([1,2,4,5])
print(x)
print(x+1)

[1 2 4 5]
[2 3 5 6]


In [80]:
x ** 3

array([  1,   8,  64, 125], dtype=int32)

In [94]:
y = np.ones(6) + 2
y

array([3., 3., 3., 3., 3., 3.])

In [100]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[3,3],[5,4],[2,5]])

# adding x and y
print('sum of x and y :\n',x*y)

sum of x and y :
 [[ 3  6]
 [15 16]
 [10 30]]


In [102]:
# multiply x and y -elementwise multiplication
print('product of x and y :\n',x*y)

product of x and y :
 [[ 3  6]
 [15 16]
 [10 30]]


In [104]:
# array multiplication
z = np.diag([1,2,3,4])
print(z * z)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [106]:
# matrix multiplication
x = np.array([[1,3,1],[3,4,3],[6,5,6]])
y = np.array([[4,4,2],[3,3,4],[4,4,3]])
print('maatrix multiplication:\n',np.matmul(x,y))

maatrix multiplication:
 [[17 17 17]
 [36 36 31]
 [63 63 50]]


### comparisions

In [109]:
x = np.array([1,2,3,4])
y = np.array([4,2,3,8])
x == y

array([False,  True,  True, False])

In [111]:
x > y

array([False, False, False, False])

In [113]:
#array-wise comparisions
x = np.array([1,2,3,4])
y = np.array([4,5,8,9])
z = np.array([3,5,7,1])

In [115]:
np.array_equal(x,y)

False

In [119]:
np.array_equal(z,x)

False

### logical operations

In [122]:
x = np.array([1,1,2,2], dtype=bool)
y = np.array([1,2,0,1], dtype=bool)

np.logical_or(x,y)

array([ True,  True,  True,  True])

In [124]:
np.logical_and(x,y)

array([ True,  True, False,  True])

### Transcendental functions

In [129]:
x = np.arange(4)
np.sin(x)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [133]:
np.log(x)

C:\Users\subha\AppData\Local\Temp\ipykernel_7728\1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [135]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

### Shape mismatch

### Basic Reductions

In [139]:
x = np.array([4,3,2,1])
np.sum(x)

10

In [141]:
#sum by rows and by columns
x = np.array([[1,2],[2,2]])
x

array([[1, 2],
       [2, 2]])

In [143]:
x.sum(axis=0)

array([3, 4])

In [150]:
x.sum(axis=1)

array([3, 4])

### Other reductions

In [153]:
x = np.array([1,2,4])
x.min()

1

In [155]:
x.max()

4

In [157]:
x.argmin()

0

In [159]:
x.argmax()

2

### Statistics

In [166]:
normal_array = np.arange(0,15,2)
print('array is ',format(normal_array))

### min
print('min element is ',np.min(normal_array))

### max
print('max element is ',np.max(normal_array))

### sum 
print('sum of elements in array is ',np.sum(normal_array))

### mean
print('mean of elements in array is ',np.mean(normal_array))

### median
print('median of elements in array is ',np.median(normal_array))

### sd 
print('standard deviation of  elements in array is ',np.std(normal_array))


array is  [ 0  2  4  6  8 10 12 14]
min element is  0
max element is  14
sum of elements in array is  56
mean of elements in array is  7.0
median of elements in array is  7.0
standard deviation of  elements in array is  4.58257569495584
